version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/data # Mount the named volume to /app/data directory
    environment:
      DATABASE_URL: "sqlite:///data/quantaste.db" # Database file inside /app/data
      DEFAULT_TICKERS: "AAPL,MSFT,GOOGL,AMZN,TSLA,NVDA"
    # depends_on:
    #   - db # Uncomment if using a separate database service like PostgreSQL

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:8000" # Communicate with backend service by its name
    depends_on:
      - backend

volumes:
  backend_data:
